<a href="https://colab.research.google.com/github/codewithkaran3/house-price-regression/blob/main/Houseprice_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# House Price Study in US ( using supply and demand factors)

In [4]:
from google.colab import files
uploaded = files.upload()

Saving Housing_data - data.csv to Housing_data - data.csv

In this model, 6 factors namely population, monthly supply of homes, house permits, mortgage rate, gdp and unemployment rates are used for the analysis of House prices.


Demand Factors:
- Population
- Unemploment rate
- mortgage rate
- gdp

supply factors:
- monthly supply of homes
- new house permits

In [5]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
import matplotlib

In [6]:
df = pd.read_csv('Housing_data - data.csv')

In [11]:
df.tail(20)

,date,target_price_index,population,monthly_supply_houses,new_permits_thousands,mortgage_rate,gdp_monthly,unempoyment_rate
244,1/5/2020,217.810,329894.0,5.3,1246.0,4.65,90.834,13.2
245,1/6/2020,218.356,330038.0,4.3,1296.0,4.85,92.504,11.0
246,1/7/2020,219.899,330199.0,3.6,1542.0,4.94,94.165,10.2
247,1/8/2020,222.735,330368.0,3.5,1522.0,4.63,95.811,8.4
248,1/9/2020,225.954,330535.0,3.5,1589.0,4.45,95.949,7.9
249,1/10/2020,229.442,330692.0,3.5,1595.0,4.41,96.081,6.9
250,1/11/2020,232.656,330829.0,4.0,1696.0,4.41,96.210,6.7
251,1/12/2020,235.583,330924.0,3.8,1758.0,4.08,96.451,6.7
252,1/1/2021,238.530,330968.0,3.6,1883.0,4.14,96.692,6.4
253,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.2
254,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
255,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0
256,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.8
257,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.9
258,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.4
259,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.2
260,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.7
261,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.6
262,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.2
263,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.9

In [22]:
df2 = df.dropna()
df2.tail(5)

,date,target_price_index,population,monthly_supply_houses,new_permits_thousands,mortgage_rate,gdp_monthly,unempoyment_rate
248,1/9/2020,225.954,330535.0,3.5,1589.0,4.45,95.949,7.9
249,1/10/2020,229.442,330692.0,3.5,1595.0,4.41,96.081,6.9
250,1/11/2020,232.656,330829.0,4.0,1696.0,4.41,96.210,6.7
251,1/12/2020,235.583,330924.0,3.8,1758.0,4.08,96.451,6.7
252,1/1/2021,238.530,330968.0,3.6,1883.0,4.14,96.692,6.4

In [26]:
df2.dtypes

date                      object
target_price_index       float64
population               float64
monthly_supply_houses    float64
new_permits_thousands    float64
mortgage_rate            float64
gdp_monthly              float64
unempoyment_rate         float64
dtype: object

In [27]:
df3 = df2.drop(columns=['date'], axis=1)

# Feature Scaling: Normalization

In [28]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df4=pd.DataFrame(scaler.fit_transform(df3), columns=df3.columns, index=df3.index) 
df4

,target_price_index,population,monthly_supply_houses,new_permits_thousands,mortgage_rate,gdp_monthly,unempoyment_rate
0,0.000000,0.000000,0.091954,0.693714,0.911488,0.970310,0.044643
1,0.005704,0.004330,0.091954,0.673714,0.930320,0.975683,0.053571
2,0.011415,0.008981,0.091954,0.650286,0.934087,0.982332,0.044643
3,0.017177,0.013631,0.103448,0.619429,0.926554,0.988707,0.026786
4,0.022649,0.018302,0.103448,0.588571,0.907721,0.992441,0.044643
...,...,...,...,...,...,...,...
248,0.908855,0.991320,0.000000,0.614857,0.214689,0.465847,0.392857
249,0.934134,0.994467,0.000000,0.618286,0.207156,0.477869,0.303571
250,0.957428,0.997214,0.057471,0.676000,0.207156,0.489617,0.285714
251,0.978642,0.999118,0.034483,0.711429,0.145009,0.511566,0.285714
252,1.000000,1.000000,0.011494,0.782857,0.156309,0.533515,0.258929

# Train- test split

In [30]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df4.drop(columns="target_price_index", axis=1), df4["target_price_index"], 
                                                    test_size= 0.20, random_state=40)

In [31]:
from sklearn.linear_model import LinearRegression
lr_clf = LinearRegression()
lr_clf.fit(X_train, y_train)
lr_clf.score(X_test, y_test)

0.9728269548202986

In [33]:
X = df4.drop(['target_price_index'], axis = 'columns')

In [34]:
y = df2.target_price_index

# K Fold Cross validation to measure accuracy of Regression models

In [35]:
from sklearn.model_selection import ShuffleSplit
from sklearn.model_selection import cross_val_score

cv = ShuffleSplit( n_splits = 5, test_size=0.2, random_state=0  )

cross_val_score(LinearRegression(), X, y, cv=cv)

array([0.95376126, 0.95467796, 0.97521828, 0.95047961, 0.97182698])

# Find best model using GridSearchCV

In [43]:
from sklearn.model_selection import GridSearchCV

from sklearn.linear_model import Lasso

from sklearn.tree import DecisionTreeRegressor

def find_best_model_using_gridsearchcv(X,y):
    algos = {
        'linear_regression' : {
            'model': LinearRegression(),
            'params': {
                'normalize': [True, False]
            }
        },
        'lasso': {
            'model': Lasso(),
            'params': {
                'alpha': [1,2],
                'selection': ['random', 'cyclic']
            }
        }
    }
    scores = []
    cv = ShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
    for algo_name, config in algos.items():
        gs =  GridSearchCV(config['model'], config['params'], cv=cv, return_train_score=False)
        gs.fit(X,y)
        scores.append({
            'model': algo_name,
            'best_score': gs.best_score_,
            'best_params': gs.best_params_
        })

    return pd.DataFrame(scores,columns=['model','best_score','best_params'])

find_best_model_using_gridsearchcv(X,y)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:155: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:155: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:155: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:155: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:155: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2. Please leave the normalize parameter to its default value to silence this warning. The default behavior of this estimator is to not do any normalization. If normalization is needed please use sklearn.preprocessing.StandardScaler instead.
  FutureWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_base.py:145: FutureWarning: 'normalize' was deprecated in version 1.0 and will be removed in 1.2.
If you wish to scale the data, use Pipeline with a StandardScaler in a preprocessing stage. To reproduce the previous behavior:

from sklearn.pipeline import make_pipeline

model = make_pipeline(StandardScaler(with_mean=False), LinearRegression())

If you wish to pass a sample_weight parameter, you need to pass it as a fit parameter to each step of the pipeline as follows:

kwargs = {s[0] + '__sample_weight': sample_weight for s in model.steps}
model.fit(X, y, **kwargs)


  FutureWarning,

               model  best_score                          best_params
0  linear_regression    0.961193                  {'normalize': True}
1              lasso    0.806721  {'alpha': 1, 'selection': 'cyclic'}

# OLS

In [38]:
import statsmodels.api as sm

In [39]:
result = sm.OLS(y_train, X_train).fit()

In [40]:
print(result.summary())

                                 OLS Regression Results
=======================================================================================
Dep. Variable:     target_price_index   R-squared (uncentered):                   0.987
Model:                            OLS   Adj. R-squared (uncentered):              0.987
Method:                 Least Squares   F-statistic:                              2547.
Date:                Fri, 09 Sep 2022   Prob (F-statistic):                   5.41e-183
Time:                        10:04:39   Log-Likelihood:                          295.71
No. Observations:                 202   AIC:                                     -579.4
Df Residuals:                     196   BIC:                                     -559.6
Df Model:                           6
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
population                0.7065      0.022     31.544      0.000       0.662       0.751
monthly_supply_houses     0.4790      0.025     19.093      0.000       0.430       0.529
new_permits_thousands     0.5863      0.023     25.256      0.000       0.541       0.632
mortgage_rate            -0.0406      0.034     -1.209      0.228      -0.107       0.026
gdp_monthly              -0.3433      0.022    -15.395      0.000      -0.387      -0.299
unempoyment_rate         -0.1763      0.026     -6.855      0.000      -0.227      -0.126
==============================================================================
Omnibus:                       11.760   Durbin-Watson:                   2.009
Prob(Omnibus):                  0.003   Jarque-Bera (JB):               12.094
Skew:                           0.565   Prob(JB):                      0.00236
Kurtosis:                       3.398   Cond. No.                         14.3
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.

# Conclusion

Prediction Model: Linear regression
Accuaracy :97.18

Positively correlated variables - population, monthly_supply_homes, new_permits


Negatively correlated variables - mortgage_rate, gdp_monthly, unempoyment_rate